### PR TITLE
Add cluster configuration option

### PR DESCRIPTION
**Pull request by hot-leaf-juice**
Adds proper support for a cluster configuration option. Thanks to @Misiu for bringing this to our attention and on working on a fix in #21 (these changes are taken from there, just without the nuget changes 😉 )

Also taken the opportunity to bump some version numbers on dependencies and remove unused imports.

### CODE REVIEW

**Comment by Misiu** [comment]
@hot-leaf-juice Thank You for fixing this and for pulling those changes. Glad I could help!

**Comment by Misiu** [comment]
@hot-leaf-juice Do You plan to push changes to NuGet? Currently latest version is 0.3.0 also Microsoft is listed as author and in copyrights. Maybe this can be changed to include Pusher as author, or Pusher Community.

**Comment by hot-leaf-juice** [comment]
@misiu Yes, the changes will be pushed to NuGet shortly, watch this space!

**Comment by Misiu** [comment]
@hot-leaf-juice awesome :) looking forward to that

**Comment by hot-leaf-juice** [comment]
@misiu the latest version (0.4.0) has been deployed to NuGet now :)

**Comment by Misiu** [comment]
Awesome :D

10.11.2016 6:36 PM "Callum Oakley" <notifications@github.com> napisał(a):

**Pull request merged**
