### PR TITLE
Rolled back the supported version of Pusher Client to .net 4.5

### PR DESCRIPTION
**Pull request by imaji**

### CODE REVIEW

**Comment by Boogier** [comment]
Great! Waiting this to appear in nuget.org :)

**Comment by Boogier** [comment]
@imaji could you please merge this and deploy new nuget package?

**Comment by imaji** [comment]
It's in the process of being merged :)

**Comment by imaji** [comment]
Hi!

Sorry, just making some tweaks, bear with me!

**Comment by imaji** [comment]
This has now been superseded by https://github.com/pusher-community/pusher-websocket-dotnet/pull/56

**Pull request closed without merging**
